// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qhrjwQiTMZgaQR_SDrVrUEffYtZ6L1Q',
    appId: '1:167483366107:web:2e511ffe4c50eea058cafe',
    messagingSenderId: '167483366107',
    projectId: 'poro2-839fe',
    authDomain: 'poro2-839fe.firebaseapp.com',
    storageBucket: 'poro2-839fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPeJh5lgWjmFScVMFBSqYHuXspWgInsM',
    appId: '1:167483366107:android:96d34ad5287fe39358cafe',
    messagingSenderId: '167483366107',
    projectId: 'poro2-839fe',
    storageBucket: 'poro2-839fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6-U9Y16KmrXhLLBFEuo0QSIdVsN-4Dtc',
    appId: '1:167483366107:ios:15396c11ecf39ae558cafe',
    messagingSenderId: '167483366107',
    projectId: 'poro2-839fe',
    storageBucket: 'poro2-839fe.firebasestorage.app',
    iosBundleId: 'com.example.poro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6-U9Y16KmrXhLLBFEuo0QSIdVsN-4Dtc',
    appId: '1:167483366107:ios:15396c11ecf39ae558cafe',
    messagingSenderId: '167483366107',
    projectId: 'poro2-839fe',
    storageBucket: 'poro2-839fe.firebasestorage.app',
    iosBundleId: 'com.example.poro2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qhrjwQiTMZgaQR_SDrVrUEffYtZ6L1Q',
    appId: '1:167483366107:web:df283b7c51ea043558cafe',
    messagingSenderId: '167483366107',
    projectId: 'poro2-839fe',
    authDomain: 'poro2-839fe.firebaseapp.com',
    storageBucket: 'poro2-839fe.firebasestorage.app',
  );
}
